### ISSUE TITLE
Empty inputs

### ISSUE THREAD

**Issue by AlwxSin** [suessflorian/gqlfetch#1]
Hey @suessflorian, thanks for the tool.

I fetched schema and found that all inputs are empty, no fields specified
```graphql
input UpdateWorkTemplateInput {
}
```

If I want to use schema for `genqlient` I need inputs, so genclient can generate proper code.

**Comment by suessflorian** [comment]
Good find, I'll give a shot at writing some tests too.

**Comment by suessflorian** [comment]
Update: I've got a reproducible example via `graph-gophers`, so we're good, just looks like there are a couple ways a server can return input fields.
