### ISSUE TITLE
error: No query string was present

### ISSUE THREAD

**Issue by eblin** [suessflorian/gqlfetch#5]
Hi there,

I keep getting this error from the server and upon further inspection this happens because the `query` operation type is being sent as uppercase `Query` 

```{"Query":"query IntrospectionQuery {\n  __schema {\n...```

Server returns

```
{
  "errors": [
    {
      "message": "No query string was present"
    }
  ]
}
```

the query works fine if operation type is sent as: `query`

```{"query":"query IntrospectionQuery {\n  __schema {\n...```

---

I'll be happy to submit a PR if needed, but it is such a minor change might just be easier for you guys to commit the change. 

I couldn't find anything on wether the [spec](https://spec.graphql.org/June2018/#sec-Language.Operations) requires this to be uppercase or lowercase but from my experience I have always seen the operation types being sent lowercase. They are also shown lowercased in the spec.

**Comment by suessflorian** [comment]
Oh no! I'll encode this correctly right away - thanks for bringing this up. Out of curiosity, what graphql server library are you using?

**Comment by eblin** [comment]
It's a remote server for a headless cms so I have no clue what they're running. 

Thanks for the update 👍
