### ISSUE TITLE
Interface arguments are not generated

### ISSUE THREAD

**Issue by oatovar** [suessflorian/gqlfetch#6]
## Description

If an `interface` field has arguments, they will not be generated. This causes errors when using the exported schema in [genqlient](https://github.com/Khan/genqlient).

## Steps to reproduce

1. Create a new go project
    ```shell
    $ mkdir sample-gengqlient-project
    $ cd sample-genqlient-project
    $ go mod init sample-genqlient-project
    ```
1. Run `go install github.com/suessflorian/gqlfetch/gqlfetch@latest`
1. Run `gqlfetch --endpoint https://gitlab.com/api/graphql > schema.graphql`
1. Run `go run github.com/Khan/genqlient@latest --init` and observe that the it is unable to init the project because of the interface and implementation argument mismatch.

**Comment by oatovar** [comment]
I have a fix for this and will open up a PR for this shortly.

**Comment by suessflorian** [comment]
PR submitted was excellent, thanks @oatovar 🙏
