### ISSUE TITLE
What license is this project released under?

### ISSUE THREAD

**Issue by oatovar** [suessflorian/gqlfetch#8]
## Description

I'm looking at using this project, but I'm unable to do so at the moment without a software license. Is the project intended to be used under a specific license?

From the GitHub [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license).

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by suessflorian** [comment]
Oh boy, I wish this to be hosted without strings attached, here is an [MIT License](https://github.com/suessflorian/gqlfetch/commit/c02b09d1ceafc1dc36689b4b4e73341154681219).
